build_and_deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Run yarn install and build
          run: |
            yarn install --frozen-lockfile
            yarn build
        - uses: FirebaseExtended/action-hosting-deploy@v0
          with:
            repoToken: "${{ secrets.GITHUB_TOKEN }}"
            firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_PSYCOAI_TEST }}"
            channelId: live
            projectId: psycoai-test
